var rawData = [
    { name: 'Nike React HyperSet Rise 4',
    discountPrice: 116,
    colorStyles: [ 'Light Redwood', 'Pink Quartz', 'White' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'React',
       'HyperSet',
       'Rise',
       '4',
       'Light Redwood',
       'Pink Quartz',
       'White',
       'React',
       'React HyperSet',
       'React HyperSet Rise' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/12178bf0-1f2a-4033-8c41-1672081669f2/react-hyperset-womens-volleyball-shoe-Hp4LWJ.jpg',
    nikeID: 100 },
  { name: 'Nike React HyperSet Rise 4',
    discountPrice: 118,
    colorStyles:
     [ 'Dark Grey', 'Pure Platinum', 'Anthracite', 'Bright Crimson' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'HyperSet',
       'Rise',
       '4',
       'Dark Grey',
       'Pure Platinum',
       'Anthracite',
       'Bright Crimson',
       'React',
       'React HyperSet',
       'React HyperSet Rise' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/12178bf0-1f2a-4033-8c41-1672081669f2/react-hyperset-womens-volleyball-shoe-Hp4LWJ.jpg',
    nikeID: 101 },
  { name: 'Nike React HyperSet Rise 4',
    discountPrice: 99,
    colorStyles: [ 'Black', 'Anthracite', 'Pink Blast', 'Black' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'HyperSet',
       'Rise',
       '4',
       'Black',
       'Anthracite',
       'Pink Blast',
       'Black',
       'React',
       'React HyperSet',
       'React HyperSet Rise' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/12178bf0-1f2a-4033-8c41-1672081669f2/react-hyperset-womens-volleyball-shoe-Hp4LWJ.jpg',
    nikeID: 102 },
  { name: 'Nike React HyperSet Rise 4',
    discountPrice: 108,
    colorStyles: [ 'Dune Red', 'Mahogany', 'Team Orange', 'Burgundy Ash' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'HyperSet',
       'Rise',
       '4',
       'Dune Red',
       'Mahogany',
       'Team Orange',
       'Burgundy Ash',
       'React',
       'React HyperSet',
       'React HyperSet Rise' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/12178bf0-1f2a-4033-8c41-1672081669f2/react-hyperset-womens-volleyball-shoe-Hp4LWJ.jpg',
    nikeID: 103 },
  { name: 'Nike React HyperSet Rise 4',
    discountPrice: 86,
    colorStyles:
     [ 'Stone Mauve',
       'Barely Rose',
       'Smokey Mauve',
       'Metallic Red Bronze' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'React',
       'HyperSet',
       'Rise',
       '4',
       'Stone Mauve',
       'Barely Rose',
       'Smokey Mauve',
       'Metallic Red Bronze',
       'React',
       'React HyperSet',
       'React HyperSet Rise' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/12178bf0-1f2a-4033-8c41-1672081669f2/react-hyperset-womens-volleyball-shoe-Hp4LWJ.jpg',
    nikeID: 104 },
  { name: 'Nike React Element 55 Shield',
    discountPrice: 111,
    colorStyles: [ 'Volt', 'White', 'Gum Light Brown', 'Volt' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Element',
       '55',
       'Shield',
       'Volt',
       'White',
       'Gum Light Brown',
       'Volt',
       'React',
       'React Element',
       'React Element 55' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/b6b37945-49c4-4f82-95e8-561147a8a6ac/react-element-55-se-womens-shoe-L5WpdL.jpg',
    nikeID: 105 },
  { name: 'Nike React Element 55 Shield',
    discountPrice: 86,
    colorStyles:
     [ 'Aura', 'Light Armory Blue', 'Mint Foam', 'Blackened Blue' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Element',
       '55',
       'Shield',
       'Aura',
       'Light Armory Blue',
       'Mint Foam',
       'Blackened Blue',
       'React',
       'React Element',
       'React Element 55' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/b6b37945-49c4-4f82-95e8-561147a8a6ac/react-element-55-se-womens-shoe-L5WpdL.jpg',
    nikeID: 106 },
  { name: 'Nike React Element 55 Shield',
    discountPrice: 109,
    colorStyles: [ 'Cosmic Clay', 'Blue Hero', 'Sail', 'Black' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Element',
       '55',
       'Shield',
       'Cosmic Clay',
       'Blue Hero',
       'Sail',
       'Black',
       'React',
       'React Element',
       'React Element 55' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/b6b37945-49c4-4f82-95e8-561147a8a6ac/react-element-55-se-womens-shoe-L5WpdL.jpg',
    nikeID: 107 },
  { name: 'Nike React Element 55 Shield',
    discountPrice: 114,
    colorStyles: [ 'Anthracite', 'Barely Grey', 'White', 'Black' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Element',
       '55',
       'Shield',
       'Anthracite',
       'Barely Grey',
       'White',
       'Black',
       'React',
       'React Element',
       'React Element 55' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/b6b37945-49c4-4f82-95e8-561147a8a6ac/react-element-55-se-womens-shoe-L5WpdL.jpg',
    nikeID: 108 },
  { name: 'Nike React Element 55 Shield',
    discountPrice: 103,
    colorStyles: [ 'Fossil', 'Black', 'Pistachio Frost', 'White' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Element',
       '55',
       'Shield',
       'Fossil',
       'Black',
       'Pistachio Frost',
       'White',
       'React',
       'React Element',
       'React Element 55' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/b6b37945-49c4-4f82-95e8-561147a8a6ac/react-element-55-se-womens-shoe-L5WpdL.jpg',
    nikeID: 109 },
  { name: 'Nike React Terra Globe',
    discountPrice: 104,
    colorStyles: [ 'White', 'Black', 'Iced Lilac', 'Noble Red' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'React',
       'Terra',
       'Globe',
       'White',
       'Black',
       'Iced Lilac',
       'Noble Red',
       'React',
       'React Terra' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 110 },
  { name: 'Nike React Terra Globe',
    discountPrice: 86,
    colorStyles: [ 'White', 'Black', 'Atomic Violet', 'Night Maroon' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Terra',
       'Globe',
       'White',
       'Black',
       'Atomic Violet',
       'Night Maroon',
       'React',
       'React Terra' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 111 },
  { name: 'Nike React Terra Globe',
    discountPrice: 82,
    colorStyles: [ 'Oil Grey', 'Black', 'Wolf Grey', 'Barely Grey' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Terra',
       'Globe',
       'Oil Grey',
       'Black',
       'Wolf Grey',
       'Barely Grey',
       'React',
       'React Terra' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 112 },
  { name: 'Nike React Terra Globe',
    discountPrice: 84,
    colorStyles: [ 'Cool Grey', 'Wolf Grey', 'White', 'Metallic Platinum' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'React',
       'Terra',
       'Globe',
       'Cool Grey',
       'Wolf Grey',
       'White',
       'Metallic Platinum',
       'React',
       'React Terra' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 113 },
  { name: 'Nike React Terra Globe',
    discountPrice: 109,
    colorStyles: [ 'Black', 'Valerian Blue', 'Vivid Purple' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'React',
       'Terra',
       'Globe',
       'Black',
       'Valerian Blue',
       'Vivid Purple',
       'React',
       'React Terra' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 114 },
  { name: 'Nike Odyssey React JoyRide CC 2',
    discountPrice: 111,
    colorStyles:
     [ 'Plum Chalk', 'Infinite Gold', 'Silver Lilac', 'Metallic Gold' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'Odyssey',
       'React',
       'JoyRide',
       'CC',
       '2',
       'Plum Chalk',
       'Infinite Gold',
       'Silver Lilac',
       'Metallic Gold',
       'Odyssey',
       'Odyssey React',
       'Odyssey React JoyRide',
       'Odyssey React JoyRide CC' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/ed0ycapngvnnbpu4pj6h/joyride-cc-mens-shoe-7pfVQF.jpg',
    nikeID: 115 },
  { name: 'Nike Odyssey React JoyRide CC 2',
    discountPrice: 93,
    colorStyles: [ 'True Berry', 'Vast Grey', 'Pink Blast', 'Black' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'Odyssey',
       'React',
       'JoyRide',
       'CC',
       '2',
       'True Berry',
       'Vast Grey',
       'Pink Blast',
       'Black',
       'Odyssey',
       'Odyssey React',
       'Odyssey React JoyRide',
       'Odyssey React JoyRide CC' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/ed0ycapngvnnbpu4pj6h/joyride-cc-mens-shoe-7pfVQF.jpg',
    nikeID: 116 },
  { name: 'Nike Odyssey React JoyRide CC 2',
    discountPrice: 106,
    colorStyles: [ 'Oil Grey', 'Black', 'Wolf Grey', 'Barely Grey' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'Odyssey',
       'React',
       'JoyRide',
       'CC',
       '2',
       'Oil Grey',
       'Black',
       'Wolf Grey',
       'Barely Grey',
       'Odyssey',
       'Odyssey React',
       'Odyssey React JoyRide',
       'Odyssey React JoyRide CC' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/ed0ycapngvnnbpu4pj6h/joyride-cc-mens-shoe-7pfVQF.jpg',
    nikeID: 117 },
  { name: 'Nike Odyssey React JoyRide CC 2',
    discountPrice: 128,
    colorStyles: [ 'Phantom', 'Barely Volt', 'Spruce Aura', 'Bio Beige' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'Odyssey',
       'React',
       'JoyRide',
       'CC',
       '2',
       'Phantom',
       'Barely Volt',
       'Spruce Aura',
       'Bio Beige',
       'Odyssey',
       'Odyssey React',
       'Odyssey React JoyRide',
       'Odyssey React JoyRide CC' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/ed0ycapngvnnbpu4pj6h/joyride-cc-mens-shoe-7pfVQF.jpg',
    nikeID: 118 },
  { name: 'Nike Odyssey React JoyRide CC 2',
    discountPrice: 126,
    colorStyles: [ 'Black', 'Anthracite', 'Pink Blast', 'Black' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'Odyssey',
       'React',
       'JoyRide',
       'CC',
       '2',
       'Black',
       'Anthracite',
       'Pink Blast',
       'Black',
       'Odyssey',
       'Odyssey React',
       'Odyssey React JoyRide',
       'Odyssey React JoyRide CC' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/ed0ycapngvnnbpu4pj6h/joyride-cc-mens-shoe-7pfVQF.jpg',
    nikeID: 119 },
  { name: 'Nike Odyssey React JoyRide CC 2',
    discountPrice: 132,
    colorStyles:
     [ 'Light Orewood Brown', 'Black', 'Villain Red', 'Hyper Crimson' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'Odyssey',
       'React',
       'JoyRide',
       'CC',
       '2',
       'Light Orewood Brown',
       'Black',
       'Villain Red',
       'Hyper Crimson',
       'Odyssey',
       'Odyssey React',
       'Odyssey React JoyRide',
       'Odyssey React JoyRide CC' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/ed0ycapngvnnbpu4pj6h/joyride-cc-mens-shoe-7pfVQF.jpg',
    nikeID: 120 },
  { name: 'Nike React Ianga Rise',
    discountPrice: 91,
    colorStyles: [ 'Black', 'Anthracite', 'Pink Blast', 'Black' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Ianga',
       'Rise',
       'Black',
       'Anthracite',
       'Pink Blast',
       'Black',
       'React',
       'React Ianga' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/flq2fuvrxzuzem0fayqd/react-ianga-mens-shoe-GBwZHW.jpg',
    nikeID: 121 },
  { name: 'Nike React Ianga Rise',
    discountPrice: 119,
    colorStyles: [ 'Pumice', 'Vast Grey', 'Celestial Gold', 'Pink Quartz' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'React',
       'Ianga',
       'Rise',
       'Pumice',
       'Vast Grey',
       'Celestial Gold',
       'Pink Quartz',
       'React',
       'React Ianga' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/flq2fuvrxzuzem0fayqd/react-ianga-mens-shoe-GBwZHW.jpg',
    nikeID: 122 },
  { name: 'Nike React Ianga Rise',
    discountPrice: 108,
    colorStyles:
     [ 'Echo Pink',
       'Metallic Red Bronze',
       'Oil Grey',
       'Metallic Red Bronze' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'React',
       'Ianga',
       'Rise',
       'Echo Pink',
       'Metallic Red Bronze',
       'Oil Grey',
       'Metallic Red Bronze',
       'React',
       'React Ianga' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/flq2fuvrxzuzem0fayqd/react-ianga-mens-shoe-GBwZHW.jpg',
    nikeID: 123 },
  { name: 'Nike React Ianga Rise',
    discountPrice: 105,
    colorStyles: [ 'Dune Red', 'Mahogany', 'Team Orange', 'Burgundy Ash' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Ianga',
       'Rise',
       'Dune Red',
       'Mahogany',
       'Team Orange',
       'Burgundy Ash',
       'React',
       'React Ianga' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/flq2fuvrxzuzem0fayqd/react-ianga-mens-shoe-GBwZHW.jpg',
    nikeID: 124 },
  { name: 'Nike React Ianga Rise',
    discountPrice: 90,
    colorStyles: [ 'Dune Red', 'Mahogany', 'Team Orange', 'Burgundy Ash' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Ianga',
       'Rise',
       'Dune Red',
       'Mahogany',
       'Team Orange',
       'Burgundy Ash',
       'React',
       'React Ianga' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/flq2fuvrxzuzem0fayqd/react-ianga-mens-shoe-GBwZHW.jpg',
    nikeID: 125 },
  { name: 'Nike Air Zoom Vomero 14',
    discountPrice: 128,
    colorStyles: [ 'Black', 'True Berry', 'White', 'Pink Blast' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Vomero',
       '14',
       'Black',
       'True Berry',
       'White',
       'Pink Blast',
       'Air',
       'Air Zoom',
       'Air Zoom Vomero' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 126 },
  { name: 'Nike Air Zoom Vomero 14',
    discountPrice: 145,
    colorStyles:
     [ 'Dark Grey', 'Pure Platinum', 'Anthracite', 'Bright Crimson' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Vomero',
       '14',
       'Dark Grey',
       'Pure Platinum',
       'Anthracite',
       'Bright Crimson',
       'Air',
       'Air Zoom',
       'Air Zoom Vomero' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 127 },
  { name: 'Nike Air Zoom Vomero 14',
    discountPrice: 166,
    colorStyles: [ 'Black', 'Photon Dust', 'Valerian Blue', 'Vivid Purple' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Vomero',
       '14',
       'Black',
       'Photon Dust',
       'Valerian Blue',
       'Vivid Purple',
       'Air',
       'Air Zoom',
       'Air Zoom Vomero' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 128 },
  { name: 'Nike Air Zoom Vomero 14',
    discountPrice: 160,
    colorStyles: [ 'Cosmic Clay', 'Blue Hero', 'Sail', 'Black' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Vomero',
       '14',
       'Cosmic Clay',
       'Blue Hero',
       'Sail',
       'Black',
       'Air',
       'Air Zoom',
       'Air Zoom Vomero' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 129 },
  { name: 'Nike Air Zoom Vomero 14',
    discountPrice: 139,
    colorStyles: [ 'Black', 'Photon Dust', 'Valerian Blue', 'Vivid Purple' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Vomero',
       '14',
       'Black',
       'Photon Dust',
       'Valerian Blue',
       'Vivid Purple',
       'Air',
       'Air Zoom',
       'Air Zoom Vomero' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 130 },
  { name: 'Nike Air Zoom Vomero 14',
    discountPrice: 143,
    colorStyles: [ 'Phantom', 'Barely Volt', 'Spruce Aura', 'Bio Beige' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Vomero',
       '14',
       'Phantom',
       'Barely Volt',
       'Spruce Aura',
       'Bio Beige',
       'Air',
       'Air Zoom',
       'Air Zoom Vomero' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 131 },
  { name: 'Nike React Ianga (SE)',
    discountPrice: 114,
    colorStyles:
     [ 'Plum Chalk', 'Infinite Gold', 'Silver Lilac', 'Metallic Gold' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'React',
       'Ianga',
       '(SE)',
       'Plum Chalk',
       'Infinite Gold',
       'Silver Lilac',
       'Metallic Gold',
       'React',
       'React Ianga' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/flq2fuvrxzuzem0fayqd/react-ianga-mens-shoe-GBwZHW.jpg',
    nikeID: 132 },
  { name: 'Nike React Ianga (SE)',
    discountPrice: 112,
    colorStyles:
     [ 'Black', 'Light Thistle', 'Pollen Rise', 'Magic Flamingo' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Ianga',
       '(SE)',
       'Black',
       'Light Thistle',
       'Pollen Rise',
       'Magic Flamingo',
       'React',
       'React Ianga' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/flq2fuvrxzuzem0fayqd/react-ianga-mens-shoe-GBwZHW.jpg',
    nikeID: 133 },
  { name: 'Nike React Ianga (SE)',
    discountPrice: 96,
    colorStyles: [ 'Phantom', 'Barely Volt', 'Spruce Aura', 'Bio Beige' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'React',
       'Ianga',
       '(SE)',
       'Phantom',
       'Barely Volt',
       'Spruce Aura',
       'Bio Beige',
       'React',
       'React Ianga' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/flq2fuvrxzuzem0fayqd/react-ianga-mens-shoe-GBwZHW.jpg',
    nikeID: 134 },
  { name: 'Nike React Ianga (SE)',
    discountPrice: 111,
    colorStyles: [ 'Volt', 'White', 'Gum Light Brown', 'Volt' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Ianga',
       '(SE)',
       'Volt',
       'White',
       'Gum Light Brown',
       'Volt',
       'React',
       'React Ianga' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/flq2fuvrxzuzem0fayqd/react-ianga-mens-shoe-GBwZHW.jpg',
    nikeID: 135 },
  { name: 'Nike React Ianga (SE)',
    discountPrice: 106,
    colorStyles: [ 'Black', 'Photon Dust', 'Valerian Blue', 'Vivid Purple' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'React',
       'Ianga',
       '(SE)',
       'Black',
       'Photon Dust',
       'Valerian Blue',
       'Vivid Purple',
       'React',
       'React Ianga' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/flq2fuvrxzuzem0fayqd/react-ianga-mens-shoe-GBwZHW.jpg',
    nikeID: 136 },
  { name: 'Nike React Ianga (SE)',
    discountPrice: 95,
    colorStyles: [ 'Black', 'White', 'University Blue', 'Black' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Ianga',
       '(SE)',
       'Black',
       'White',
       'University Blue',
       'Black',
       'React',
       'React Ianga' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/flq2fuvrxzuzem0fayqd/react-ianga-mens-shoe-GBwZHW.jpg',
    nikeID: 137 },
  { name: 'Nike Air Zoom Fly 3 Rise',
    discountPrice: 164,
    colorStyles: [ 'Half Blue', 'White', 'Black' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Fly',
       '3',
       'Rise',
       'Half Blue',
       'White',
       'Black',
       'Air',
       'Air Zoom',
       'Air Zoom Fly',
       'Air Zoom Fly 3' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/rga8wrta1yx8x4biuwlw/zoom-fly-3-premium-mens-running-shoe-xsmTcQ.jpg',
    nikeID: 138 },
  { name: 'Nike Air Zoom Fly 3 Rise',
    discountPrice: 175,
    colorStyles: [ 'Beechtree', 'Cargo Khaki', 'Bright Crimson', 'Off Noir' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Fly',
       '3',
       'Rise',
       'Beechtree',
       'Cargo Khaki',
       'Bright Crimson',
       'Off Noir',
       'Air',
       'Air Zoom',
       'Air Zoom Fly',
       'Air Zoom Fly 3' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/rga8wrta1yx8x4biuwlw/zoom-fly-3-premium-mens-running-shoe-xsmTcQ.jpg',
    nikeID: 139 },
  { name: 'Nike Air Zoom Fly 3 Rise',
    discountPrice: 141,
    colorStyles:
     [ 'Dark Grey', 'Pure Platinum', 'Anthracite', 'Bright Crimson' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Fly',
       '3',
       'Rise',
       'Dark Grey',
       'Pure Platinum',
       'Anthracite',
       'Bright Crimson',
       'Air',
       'Air Zoom',
       'Air Zoom Fly',
       'Air Zoom Fly 3' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/rga8wrta1yx8x4biuwlw/zoom-fly-3-premium-mens-running-shoe-xsmTcQ.jpg',
    nikeID: 140 },
  { name: 'Nike Air Zoom Fly 3 Rise',
    discountPrice: 176,
    colorStyles: [ 'Light Redwood', 'Pink Quartz', 'White' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Fly',
       '3',
       'Rise',
       'Light Redwood',
       'Pink Quartz',
       'White',
       'Air',
       'Air Zoom',
       'Air Zoom Fly',
       'Air Zoom Fly 3' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/rga8wrta1yx8x4biuwlw/zoom-fly-3-premium-mens-running-shoe-xsmTcQ.jpg',
    nikeID: 141 },
  { name: 'Nike Air Zoom Fly 3 Rise',
    discountPrice: 172,
    colorStyles: [ 'Dune Red', 'Mahogany', 'Team Orange', 'Burgundy Ash' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Fly',
       '3',
       'Rise',
       'Dune Red',
       'Mahogany',
       'Team Orange',
       'Burgundy Ash',
       'Air',
       'Air Zoom',
       'Air Zoom Fly',
       'Air Zoom Fly 3' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/rga8wrta1yx8x4biuwlw/zoom-fly-3-premium-mens-running-shoe-xsmTcQ.jpg',
    nikeID: 142 },
  { name: 'Nike Air Zoom Fly 3 Rise',
    discountPrice: 169,
    colorStyles: [ 'White', 'Black', 'Atomic Violet', 'Night Maroon' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Fly',
       '3',
       'Rise',
       'White',
       'Black',
       'Atomic Violet',
       'Night Maroon',
       'Air',
       'Air Zoom',
       'Air Zoom Fly',
       'Air Zoom Fly 3' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/rga8wrta1yx8x4biuwlw/zoom-fly-3-premium-mens-running-shoe-xsmTcQ.jpg',
    nikeID: 143 },
  { name: 'Nike Free RN Motion 3.0',
    discountPrice: 78,
    colorStyles:
     [ 'White', 'Summit White', 'Laser Fuchsia', 'Psychic Purple' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'Motion',
       '3.0',
       'White',
       'Summit White',
       'Laser Fuchsia',
       'Psychic Purple',
       'Free',
       'Free RN',
       'Free RN Motion' ],
    image:
     'https://c.static-nike.com/a/images/t_PDP_1280_v1/f_auto/ylhx3vwhcimfdx02cj1r/free-rn-motion-flyknit-2018-mens-running-shoe-L0LA7L.jpg',
    nikeID: 144 },
    { name: 'Nike Free RN Motion 3.0',
    discountPrice: 78,
    colorStyles:
     [ 'Black', 'Thunder Grey', 'Light Carbon', 'Bright Ceramic' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'Motion',
       '3.0',
       'Black',
       'Thunder Grey',
       'Light Carbon',
       'Bright Ceramic',
       'Free',
       'Free RN',
       'Free RN Motion' ],
    image:
     'https://c.static-nike.com/a/images/t_PDP_1280_v1/f_auto/ylhx3vwhcimfdx02cj1r/free-rn-motion-flyknit-2018-mens-running-shoe-L0LA7L.jpg',
    nikeID: 145 },
  { name: 'Nike Free RN Motion 3.0',
    discountPrice: 86,
    colorStyles: [ 'Oil Grey', 'Black', 'Wolf Grey', 'Barely Grey' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'Motion',
       '3.0',
       'Oil Grey',
       'Black',
       'Wolf Grey',
       'Barely Grey',
       'Free',
       'Free RN',
       'Free RN Motion' ],
    image:
     'https://c.static-nike.com/a/images/t_PDP_1280_v1/f_auto/ylhx3vwhcimfdx02cj1r/free-rn-motion-flyknit-2018-mens-running-shoe-L0LA7L.jpg',
    nikeID: 146 },
  { name: 'Nike Free RN Motion 3.0',
    discountPrice: 75,
    colorStyles:
     [ 'Pure Platinum', 'White', 'Yellow Pulse', 'Psychic Purple' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'Motion',
       '3.0',
       'Pure Platinum',
       'White',
       'Yellow Pulse',
       'Psychic Purple',
       'Free',
       'Free RN',
       'Free RN Motion' ],
    image:
     'https://c.static-nike.com/a/images/t_PDP_1280_v1/f_auto/ylhx3vwhcimfdx02cj1r/free-rn-motion-flyknit-2018-mens-running-shoe-L0LA7L.jpg',
    nikeID: 147 },
  { name: 'Nike Free RN Motion 3.0',
    discountPrice: 79,
    colorStyles: [ 'True Berry', 'Vast Grey', 'Pink Blast', 'Black' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'Motion',
       '3.0',
       'True Berry',
       'Vast Grey',
       'Pink Blast',
       'Black',
       'Free',
       'Free RN',
       'Free RN Motion' ],
    image:
     'https://c.static-nike.com/a/images/t_PDP_1280_v1/f_auto/ylhx3vwhcimfdx02cj1r/free-rn-motion-flyknit-2018-mens-running-shoe-L0LA7L.jpg',
    nikeID: 148 },
  { name: 'Nike Free RN',
    discountPrice: 57,
    colorStyles: [ 'Black', 'Thunder Grey', 'White' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike', 'Free', 'RN', 'Black', 'Thunder Grey', 'White', 'Free' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/g1wtf4sgnowagkjnnea1/free-rn-flyknit-3-womens-running-shoe-TSXbz2.jpg',
    nikeID: 149 },
  { name: 'Nike Free RN',
    discountPrice: 54,
    colorStyles:
     [ 'Wolf Grey', 'Cool Grey', 'Ocean Cube', 'Metallic Cool Grey' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'Wolf Grey',
       'Cool Grey',
       'Ocean Cube',
       'Metallic Cool Grey',
       'Free' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/g1wtf4sgnowagkjnnea1/free-rn-flyknit-3-womens-running-shoe-TSXbz2.jpg',
    nikeID: 150 },
  { name: 'Nike Free RN',
    discountPrice: 57,
    colorStyles: [ 'Aura', 'Mint Foam', 'Speed Yellow', 'Blackened Blue' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'Aura',
       'Mint Foam',
       'Speed Yellow',
       'Blackened Blue',
       'Free' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/g1wtf4sgnowagkjnnea1/free-rn-flyknit-3-womens-running-shoe-TSXbz2.jpg',
    nikeID: 151 },
  { name: 'Nike Free RN',
    discountPrice: 62,
    colorStyles: [ 'Team Red', 'White', 'Gum Light Brown', 'Team Red' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'Team Red',
       'White',
       'Gum Light Brown',
       'Team Red',
       'Free' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/g1wtf4sgnowagkjnnea1/free-rn-flyknit-3-womens-running-shoe-TSXbz2.jpg',
    nikeID: 152 },
  { name: 'Nike Free RN',
    discountPrice: 54,
    colorStyles: [ 'Black', 'Cosmic Fuchsia', 'Limelight', 'Hyper Pink' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'Black',
       'Cosmic Fuchsia',
       'Limelight',
       'Hyper Pink',
       'Free' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/g1wtf4sgnowagkjnnea1/free-rn-flyknit-3-womens-running-shoe-TSXbz2.jpg',
    nikeID: 153 },
  { name: 'Nike React A.I.R (SE)',
    discountPrice: 106,
    colorStyles: [ 'Black', 'Cosmic Fuchsia', 'Limelight', 'Hyper Pink' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'A.I.R',
       '(SE)',
       'Black',
       'Cosmic Fuchsia',
       'Limelight',
       'Hyper Pink',
       'React',
       'React A.I.R' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/8a2d0ef2-53ea-4a8c-873d-acd6d7c23f25/air-max-270-react-eng-mens-shoe-CPRm5W.jpg',
    nikeID: 154 },
  { name: 'Nike React A.I.R (SE)',
    discountPrice: 105,
    colorStyles: [ 'Half Blue', 'White', 'Black' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'React',
       'A.I.R',
       '(SE)',
       'Half Blue',
       'White',
       'Black',
       'React',
       'React A.I.R' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/8a2d0ef2-53ea-4a8c-873d-acd6d7c23f25/air-max-270-react-eng-mens-shoe-CPRm5W.jpg',
    nikeID: 155 },
  { name: 'Nike React A.I.R (SE)',
    discountPrice: 94,
    colorStyles: [ 'Beechtree', 'Cargo Khaki', 'Bright Crimson', 'Off Noir' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'A.I.R',
       '(SE)',
       'Beechtree',
       'Cargo Khaki',
       'Bright Crimson',
       'Off Noir',
       'React',
       'React A.I.R' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/8a2d0ef2-53ea-4a8c-873d-acd6d7c23f25/air-max-270-react-eng-mens-shoe-CPRm5W.jpg',
    nikeID: 156 },
  { name: 'Nike React A.I.R (SE)',
    discountPrice: 96,
    colorStyles:
     [ 'White', 'Summit White', 'Laser Fuchsia', 'Psychic Purple' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'React',
       'A.I.R',
       '(SE)',
       'White',
       'Summit White',
       'Laser Fuchsia',
       'Psychic Purple',
       'React',
       'React A.I.R' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/8a2d0ef2-53ea-4a8c-873d-acd6d7c23f25/air-max-270-react-eng-mens-shoe-CPRm5W.jpg',
    nikeID: 157 },
  { name: 'Nike React A.I.R (SE)',
    discountPrice: 107,
    colorStyles: [ 'Black', 'Racer Blue', 'Atmosphere Grey', 'Black' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'A.I.R',
       '(SE)',
       'Black',
       'Racer Blue',
       'Atmosphere Grey',
       'Black',
       'React',
       'React A.I.R' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/8a2d0ef2-53ea-4a8c-873d-acd6d7c23f25/air-max-270-react-eng-mens-shoe-CPRm5W.jpg',
    nikeID: 158 },
  { name: 'Nike React Terra Globe 3',
    discountPrice: 108,
    colorStyles:
     [ 'Ocean Cube', 'Pure Platinum', 'White', 'Metallic Cool Grey' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'React',
       'Terra',
       'Globe',
       '3',
       'Ocean Cube',
       'Pure Platinum',
       'White',
       'Metallic Cool Grey',
       'React',
       'React Terra',
       'React Terra Globe' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 159 },
  { name: 'Nike React Terra Globe 3',
    discountPrice: 126,
    colorStyles: [ 'Team Red', 'White', 'Gum Light Brown', 'Team Red' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Terra',
       'Globe',
       '3',
       'Team Red',
       'White',
       'Gum Light Brown',
       'Team Red',
       'React',
       'React Terra',
       'React Terra Globe' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 160 },
  { name: 'Nike React Terra Globe 3',
    discountPrice: 121,
    colorStyles: [ 'Dune Red', 'Mahogany', 'Team Orange', 'Burgundy Ash' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Terra',
       'Globe',
       '3',
       'Dune Red',
       'Mahogany',
       'Team Orange',
       'Burgundy Ash',
       'React',
       'React Terra',
       'React Terra Globe' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 161 },
  { name: 'Nike React Terra Globe 3',
    discountPrice: 97,
    colorStyles: [ 'Pistachio Frost', 'White', 'Black' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Terra',
       'Globe',
       '3',
       'Pistachio Frost',
       'White',
       'Black',
       'React',
       'React Terra',
       'React Terra Globe' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 162 },
  { name: 'Nike React Terra Globe 3',
    discountPrice: 97,
    colorStyles: [ 'Anthracite', 'Barely Grey', 'White', 'Black' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Terra',
       'Globe',
       '3',
       'Anthracite',
       'Barely Grey',
       'White',
       'Black',
       'React',
       'React Terra',
       'React Terra Globe' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 163 },
  { name: 'Nike React Terra Globe 3',
    discountPrice: 127,
    colorStyles: [ 'Pistachio Frost', 'White', 'Black' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'React',
       'Terra',
       'Globe',
       '3',
       'Pistachio Frost',
       'White',
       'Black',
       'React',
       'React Terra',
       'React Terra Globe' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 164 },
  { name: 'Nike Air Zoom Freak Rise',
    discountPrice: 165,
    colorStyles: [ 'Black', 'Racer Blue', 'Atmosphere Grey', 'Black' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Freak',
       'Rise',
       'Black',
       'Racer Blue',
       'Atmosphere Grey',
       'Black',
       'Air',
       'Air Zoom',
       'Air Zoom Freak' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/reicequq4wevqtgtxpi6/zoom-freak-1-basketball-shoe-tmk8Hw.jpg',
    nikeID: 165 },
  { name: 'Nike Air Zoom Freak Rise',
    discountPrice: 166,
    colorStyles:
     [ 'Wolf Grey', 'Cool Grey', 'Ocean Cube', 'Metallic Cool Grey' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Freak',
       'Rise',
       'Wolf Grey',
       'Cool Grey',
       'Ocean Cube',
       'Metallic Cool Grey',
       'Air',
       'Air Zoom',
       'Air Zoom Freak' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/reicequq4wevqtgtxpi6/zoom-freak-1-basketball-shoe-tmk8Hw.jpg',
    nikeID: 166 },
  { name: 'Nike Air Zoom Freak Rise',
    discountPrice: 151,
    colorStyles: [ 'Black', 'Cosmic Fuchsia', 'Limelight', 'Hyper Pink' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Freak',
       'Rise',
       'Black',
       'Cosmic Fuchsia',
       'Limelight',
       'Hyper Pink',
       'Air',
       'Air Zoom',
       'Air Zoom Freak' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/reicequq4wevqtgtxpi6/zoom-freak-1-basketball-shoe-tmk8Hw.jpg',
    nikeID: 167 },
  { name: 'Nike Air Zoom Freak Rise',
    discountPrice: 137,
    colorStyles: [ 'Black', 'True Berry', 'White', 'Pink Blast' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Freak',
       'Rise',
       'Black',
       'True Berry',
       'White',
       'Pink Blast',
       'Air',
       'Air Zoom',
       'Air Zoom Freak' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/reicequq4wevqtgtxpi6/zoom-freak-1-basketball-shoe-tmk8Hw.jpg',
    nikeID: 168 },
  { name: 'Nike Air Zoom Freak Rise',
    discountPrice: 142,
    colorStyles: [ 'Dune Red', 'Mahogany', 'Team Orange', 'Burgundy Ash' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Freak',
       'Rise',
       'Dune Red',
       'Mahogany',
       'Team Orange',
       'Burgundy Ash',
       'Air',
       'Air Zoom',
       'Air Zoom Freak' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/reicequq4wevqtgtxpi6/zoom-freak-1-basketball-shoe-tmk8Hw.jpg',
    nikeID: 169 },
  { name: 'Nike Air Zoom Freak Rise',
    discountPrice: 155,
    colorStyles: [ 'White', 'Black', 'Atomic Violet', 'Night Maroon' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Freak',
       'Rise',
       'White',
       'Black',
       'Atomic Violet',
       'Night Maroon',
       'Air',
       'Air Zoom',
       'Air Zoom Freak' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/reicequq4wevqtgtxpi6/zoom-freak-1-basketball-shoe-tmk8Hw.jpg',
    nikeID: 170 },
  { name: 'Nike Zoom Vomero 14 FlyKnit',
    discountPrice: 140,
    colorStyles: [ 'Half Blue', 'White', 'Black' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Zoom',
       'Vomero',
       '14',
       'FlyKnit',
       'Half Blue',
       'White',
       'Black',
       'Zoom',
       'Zoom Vomero',
       'Zoom Vomero 14' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 171 },
  { name: 'Nike Zoom Vomero 14 FlyKnit',
    discountPrice: 152,
    colorStyles:
     [ 'Ocean Cube', 'Pure Platinum', 'White', 'Metallic Cool Grey' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Zoom',
       'Vomero',
       '14',
       'FlyKnit',
       'Ocean Cube',
       'Pure Platinum',
       'White',
       'Metallic Cool Grey',
       'Zoom',
       'Zoom Vomero',
       'Zoom Vomero 14' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 172 },
  { name: 'Nike Zoom Vomero 14 FlyKnit',
    discountPrice: 168,
    colorStyles: [ 'Beechtree', 'Cargo Khaki', 'Bright Crimson', 'Off Noir' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Zoom',
       'Vomero',
       '14',
       'FlyKnit',
       'Beechtree',
       'Cargo Khaki',
       'Bright Crimson',
       'Off Noir',
       'Zoom',
       'Zoom Vomero',
       'Zoom Vomero 14' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 173 },
  { name: 'Nike Zoom Vomero 14 FlyKnit',
    discountPrice: 146,
    colorStyles: [ 'Black', 'Anthracite', 'Pink Blast', 'Black' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Zoom',
       'Vomero',
       '14',
       'FlyKnit',
       'Black',
       'Anthracite',
       'Pink Blast',
       'Black',
       'Zoom',
       'Zoom Vomero',
       'Zoom Vomero 14' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 174 },
  { name: 'Nike Zoom Vomero 14 FlyKnit',
    discountPrice: 168,
    colorStyles: [ 'Black', 'True Berry', 'White', 'Pink Blast' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Zoom',
       'Vomero',
       '14',
       'FlyKnit',
       'Black',
       'True Berry',
       'White',
       'Pink Blast',
       'Zoom',
       'Zoom Vomero',
       'Zoom Vomero 14' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 175 },
  { name: 'Nike Jordan React Havoc',
    discountPrice: 92,
    colorStyles: [ 'Black', 'Racer Blue', 'Atmosphere Grey', 'Black' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'Jordan',
       'React',
       'Havoc',
       'Black',
       'Racer Blue',
       'Atmosphere Grey',
       'Black',
       'Jordan',
       'Jordan React' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 176 },
  { name: 'Nike Jordan React Havoc',
    discountPrice: 94,
    colorStyles: [ 'Fossil', 'Black', 'Pistachio Frost', 'White' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'Jordan',
       'React',
       'Havoc',
       'Fossil',
       'Black',
       'Pistachio Frost',
       'White',
       'Jordan',
       'Jordan React' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 177 },
  { name: 'Nike Jordan React Havoc',
    discountPrice: 83,
    colorStyles: [ 'Pumice', 'Vast Grey', 'Celestial Gold', 'Pink Quartz' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'Jordan',
       'React',
       'Havoc',
       'Pumice',
       'Vast Grey',
       'Celestial Gold',
       'Pink Quartz',
       'Jordan',
       'Jordan React' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 178 },
  { name: 'Nike Jordan React Havoc',
    discountPrice: 93,
    colorStyles: [ 'Half Blue', 'White', 'Black' ],
    type: 'Women Shoe',
    collection:
     [ 'Nike',
       'Jordan',
       'React',
       'Havoc',
       'Half Blue',
       'White',
       'Black',
       'Jordan',
       'Jordan React' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 179 },
  { name: 'Nike Jordan React Havoc',
    discountPrice: 81,
    colorStyles: [ 'Black', 'Cosmic Fuchsia', 'Limelight', 'Hyper Pink' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'Jordan',
       'React',
       'Havoc',
       'Black',
       'Cosmic Fuchsia',
       'Limelight',
       'Hyper Pink',
       'Jordan',
       'Jordan React' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 180 },
  { name: 'Nike Jordan React Havoc',
    discountPrice: 94,
    colorStyles: [ 'Aura', 'Mint Foam', 'Speed Yellow', 'Blackened Blue' ],
    type: 'Men Shoe',
    collection:
     [ 'Nike',
       'Jordan',
       'React',
       'Havoc',
       'Aura',
       'Mint Foam',
       'Speed Yellow',
       'Blackened Blue',
       'Jordan',
       'Jordan React' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/shatsnczqnppw5bno7o3/epic-react-flyknit-2-mens-running-shoe-2S0Cn1.jpg',
    nikeID: 181 },
  { name: 'Nike Air Zoom Pegasus FlyEase Trail',
    discountPrice: 147,
    colorStyles: [ 'Black', 'Photon Dust', 'Valerian Blue', 'Vivid Purple' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Pegasus',
       'FlyEase',
       'Trail',
       'Black',
       'Photon Dust',
       'Valerian Blue',
       'Vivid Purple',
       'Air',
       'Air Zoom',
       'Air Zoom Pegasus',
       'Air Zoom Pegasus FlyEase' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/39530e3c-2330-48b9-a7a6-72eb0e8c35ae/air-zoom-pegasus-36-flyease-mens-running-shoe-1Fb6sV.jpg',
    nikeID: 182 },
  { name: 'Nike Air Zoom Pegasus FlyEase Trail',
    discountPrice: 153,
    colorStyles: [ 'Light Redwood', 'Pink Quartz', 'White' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Pegasus',
       'FlyEase',
       'Trail',
       'Light Redwood',
       'Pink Quartz',
       'White',
       'Air',
       'Air Zoom',
       'Air Zoom Pegasus',
       'Air Zoom Pegasus FlyEase' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/39530e3c-2330-48b9-a7a6-72eb0e8c35ae/air-zoom-pegasus-36-flyease-mens-running-shoe-1Fb6sV.jpg',
    nikeID: 183 },
  { name: 'Nike Air Zoom Pegasus FlyEase Trail',
    discountPrice: 141,
    colorStyles: [ 'Black', 'True Berry', 'White', 'Pink Blast' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Pegasus',
       'FlyEase',
       'Trail',
       'Black',
       'True Berry',
       'White',
       'Pink Blast',
       'Air',
       'Air Zoom',
       'Air Zoom Pegasus',
       'Air Zoom Pegasus FlyEase' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/39530e3c-2330-48b9-a7a6-72eb0e8c35ae/air-zoom-pegasus-36-flyease-mens-running-shoe-1Fb6sV.jpg',
    nikeID: 184 },
  { name: 'Nike Air Zoom Pegasus FlyEase Trail',
    discountPrice: 151,
    colorStyles:
     [ 'Black', 'Light Thistle', 'Pollen Rise', 'Magic Flamingo' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Pegasus',
       'FlyEase',
       'Trail',
       'Black',
       'Light Thistle',
       'Pollen Rise',
       'Magic Flamingo',
       'Air',
       'Air Zoom',
       'Air Zoom Pegasus',
       'Air Zoom Pegasus FlyEase' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/39530e3c-2330-48b9-a7a6-72eb0e8c35ae/air-zoom-pegasus-36-flyease-mens-running-shoe-1Fb6sV.jpg',
    nikeID: 185 },
  { name: 'Nike Air Zoom Pegasus FlyEase Trail',
    discountPrice: 148,
    colorStyles:
     [ 'Light Orewood Brown', 'Black', 'Villain Red', 'Hyper Crimson' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Pegasus',
       'FlyEase',
       'Trail',
       'Light Orewood Brown',
       'Black',
       'Villain Red',
       'Hyper Crimson',
       'Air',
       'Air Zoom',
       'Air Zoom Pegasus',
       'Air Zoom Pegasus FlyEase' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/39530e3c-2330-48b9-a7a6-72eb0e8c35ae/air-zoom-pegasus-36-flyease-mens-running-shoe-1Fb6sV.jpg',
    nikeID: 186 },
  { name: 'Nike Air Zoom Pegasus FlyEase Trail',
    discountPrice: 176,
    colorStyles: [ 'Black', 'Racer Blue', 'Atmosphere Grey', 'Black' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Pegasus',
       'FlyEase',
       'Trail',
       'Black',
       'Racer Blue',
       'Atmosphere Grey',
       'Black',
       'Air',
       'Air Zoom',
       'Air Zoom Pegasus',
       'Air Zoom Pegasus FlyEase' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/39530e3c-2330-48b9-a7a6-72eb0e8c35ae/air-zoom-pegasus-36-flyease-mens-running-shoe-1Fb6sV.jpg',
    nikeID: 187 },
  { name: 'Nike Free RN NRG',
    discountPrice: 74,
    colorStyles: [ 'Pumice', 'Vast Grey', 'Celestial Gold', 'Pink Quartz' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'NRG',
       'Pumice',
       'Vast Grey',
       'Celestial Gold',
       'Pink Quartz',
       'Free',
       'Free RN' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/pllreyrjt8klklnvmde7/free-rn-flyknit-3-nrg-mens-running-shoe-RBSCsl.jpg',
    nikeID: 188 },
  { name: 'Nike Free RN NRG',
    discountPrice: 68,
    colorStyles:
     [ 'Sky Grey', 'Vast Grey', 'Obsidian Mist', 'Particle Grey' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'NRG',
       'Sky Grey',
       'Vast Grey',
       'Obsidian Mist',
       'Particle Grey',
       'Free',
       'Free RN' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/pllreyrjt8klklnvmde7/free-rn-flyknit-3-nrg-mens-running-shoe-RBSCsl.jpg',
    nikeID: 189 },
    { name: 'Nike Free RN NRG',
    discountPrice: 68,
    colorStyles: [ 'Black', 'True Berry', 'White', 'Pink Blast' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'NRG',
       'Black',
       'True Berry',
       'White',
       'Pink Blast',
       'Free',
       'Free RN' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/pllreyrjt8klklnvmde7/free-rn-flyknit-3-nrg-mens-running-shoe-RBSCsl.jpg',
    nikeID: 190 },
  { name: 'Nike Free RN NRG',
    discountPrice: 74,
    colorStyles: [ 'Black', 'Racer Blue', 'Atmosphere Grey', 'Black' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'NRG',
       'Black',
       'Racer Blue',
       'Atmosphere Grey',
       'Black',
       'Free',
       'Free RN' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/pllreyrjt8klklnvmde7/free-rn-flyknit-3-nrg-mens-running-shoe-RBSCsl.jpg',
    nikeID: 191 },
  { name: 'Nike Free RN NRG',
    discountPrice: 65,
    colorStyles: [ 'Pure Platinum', 'Lava Glow', 'Summit White' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'NRG',
       'Pure Platinum',
       'Lava Glow',
       'Summit White',
       'Free',
       'Free RN' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/pllreyrjt8klklnvmde7/free-rn-flyknit-3-nrg-mens-running-shoe-RBSCsl.jpg',
    nikeID: 192 },
  { name: 'Nike Free RN NRG',
    discountPrice: 77,
    colorStyles: [ 'Beechtree', 'Cargo Khaki', 'Bright Crimson', 'Off Noir' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'NRG',
       'Beechtree',
       'Cargo Khaki',
       'Bright Crimson',
       'Off Noir',
       'Free',
       'Free RN' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/pllreyrjt8klklnvmde7/free-rn-flyknit-3-nrg-mens-running-shoe-RBSCsl.jpg',
    nikeID: 193 },
  { name: 'Nike Free RN NRG',
    discountPrice: 67,
    colorStyles: [ 'Pistachio Frost', 'White', 'Black' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'NRG',
       'Pistachio Frost',
       'White',
       'Black',
       'Free',
       'Free RN' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/pllreyrjt8klklnvmde7/free-rn-flyknit-3-nrg-mens-running-shoe-RBSCsl.jpg',
    nikeID: 194 },
  { name: 'Nike Free RN NRG',
    discountPrice: 67,
    colorStyles:
     [ 'Stone Mauve',
       'Barely Rose',
       'Smokey Mauve',
       'Metallic Red Bronze' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'NRG',
       'Stone Mauve',
       'Barely Rose',
       'Smokey Mauve',
       'Metallic Red Bronze',
       'Free',
       'Free RN' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/pllreyrjt8klklnvmde7/free-rn-flyknit-3-nrg-mens-running-shoe-RBSCsl.jpg',
    nikeID: 195 },
  { name: 'Nike Free RN NRG',
    discountPrice: 60,
    colorStyles: [ 'Pistachio Frost', 'White', 'Black' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'NRG',
       'Pistachio Frost',
       'White',
       'Black',
       'Free',
       'Free RN' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/pllreyrjt8klklnvmde7/free-rn-flyknit-3-nrg-mens-running-shoe-RBSCsl.jpg',
    nikeID: 196 },
  { name: 'Nike Free RN NRG',
    discountPrice: 68,
    colorStyles:
     [ 'Pure Platinum', 'White', 'Yellow Pulse', 'Psychic Purple' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'NRG',
       'Pure Platinum',
       'White',
       'Yellow Pulse',
       'Psychic Purple',
       'Free',
       'Free RN' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/pllreyrjt8klklnvmde7/free-rn-flyknit-3-nrg-mens-running-shoe-RBSCsl.jpg',
    nikeID: 197 },
  { name: 'Nike Free RN NRG',
    discountPrice: 79,
    colorStyles:
     [ 'Dark Grey', 'Pure Platinum', 'Anthracite', 'Bright Crimson' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'NRG',
       'Dark Grey',
       'Pure Platinum',
       'Anthracite',
       'Bright Crimson',
       'Free',
       'Free RN' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/pllreyrjt8klklnvmde7/free-rn-flyknit-3-nrg-mens-running-shoe-RBSCsl.jpg',
    nikeID: 198 },
  { name: 'Nike Free RN NRG',
    discountPrice: 78,
    colorStyles: [ 'Phantom', 'Light Bone', 'Black' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Free',
       'RN',
       'NRG',
       'Phantom',
       'Light Bone',
       'Black',
       'Free',
       'Free RN' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/pllreyrjt8klklnvmde7/free-rn-flyknit-3-nrg-mens-running-shoe-RBSCsl.jpg',
    nikeID: 199 },
  { name: 'Nike Air Zoom Vomero 14 FlyKnit',
    discountPrice: 168,
    colorStyles: [ 'Atmosphere Grey', 'Thunder Grey', 'Vast Grey' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Vomero',
       '14',
       'FlyKnit',
       'Atmosphere Grey',
       'Thunder Grey',
       'Vast Grey',
       'Air',
       'Air Zoom',
       'Air Zoom Vomero',
       'Air Zoom Vomero 14' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 200 },
  { name: 'Nike Air Zoom Vomero 14 FlyKnit',
    discountPrice: 159,
    colorStyles:
     [ 'Stone Mauve',
       'Barely Rose',
       'Smokey Mauve',
       'Metallic Red Bronze' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Vomero',
       '14',
       'FlyKnit',
       'Stone Mauve',
       'Barely Rose',
       'Smokey Mauve',
       'Metallic Red Bronze',
       'Air',
       'Air Zoom',
       'Air Zoom Vomero',
       'Air Zoom Vomero 14' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 201 },
  { name: 'Nike Air Zoom Vomero 14 FlyKnit',
    discountPrice: 147,
    colorStyles: [ 'Volt', 'White', 'Gum Light Brown', 'Volt' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Vomero',
       '14',
       'FlyKnit',
       'Volt',
       'White',
       'Gum Light Brown',
       'Volt',
       'Air',
       'Air Zoom',
       'Air Zoom Vomero',
       'Air Zoom Vomero 14' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 202 },
  { name: 'Nike Air Zoom Vomero 14 FlyKnit',
    discountPrice: 155,
    colorStyles: [ 'Team Red', 'White', 'Gum Light Brown', 'Team Red' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Vomero',
       '14',
       'FlyKnit',
       'Team Red',
       'White',
       'Gum Light Brown',
       'Team Red',
       'Air',
       'Air Zoom',
       'Air Zoom Vomero',
       'Air Zoom Vomero 14' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 203 },
  { name: 'Nike Air Zoom Vomero 14 FlyKnit',
    discountPrice: 151,
    colorStyles: [ 'Laser Crimson', 'Platinum Tint', 'Track Red', 'White' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Vomero',
       '14',
       'FlyKnit',
       'Laser Crimson',
       'Platinum Tint',
       'Track Red',
       'White',
       'Air',
       'Air Zoom',
       'Air Zoom Vomero',
       'Air Zoom Vomero 14' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 204 },
  { name: 'Nike Air Zoom Vomero 14 FlyKnit',
    discountPrice: 135,
    colorStyles: [ 'Black', 'Photon Dust', 'Valerian Blue', 'Vivid Purple' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Vomero',
       '14',
       'FlyKnit',
       'Black',
       'Photon Dust',
       'Valerian Blue',
       'Vivid Purple',
       'Air',
       'Air Zoom',
       'Air Zoom Vomero',
       'Air Zoom Vomero 14' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/i1-66e2e324-bd18-4a75-b252-b8cf5c039006/air-zoom-vomero-14-womens-running-shoe-hK53Km.jpg',
    nikeID: 205 },
  { name: 'Nike Air Zoom Pegasus FlyEase FlyKnit',
    discountPrice: 175,
    colorStyles: [ 'Black', 'Anthracite', 'Pink Blast', 'Black' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Pegasus',
       'FlyEase',
       'FlyKnit',
       'Black',
       'Anthracite',
       'Pink Blast',
       'Black',
       'Air',
       'Air Zoom',
       'Air Zoom Pegasus',
       'Air Zoom Pegasus FlyEase' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/39530e3c-2330-48b9-a7a6-72eb0e8c35ae/air-zoom-pegasus-36-flyease-mens-running-shoe-1Fb6sV.jpg',
    nikeID: 206 },
  { name: 'Nike Air Zoom Pegasus FlyEase FlyKnit',
    discountPrice: 179,
    colorStyles: [ 'True Berry', 'Vast Grey', 'Pink Blast', 'Black' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Pegasus',
       'FlyEase',
       'FlyKnit',
       'True Berry',
       'Vast Grey',
       'Pink Blast',
       'Black',
       'Air',
       'Air Zoom',
       'Air Zoom Pegasus',
       'Air Zoom Pegasus FlyEase' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/39530e3c-2330-48b9-a7a6-72eb0e8c35ae/air-zoom-pegasus-36-flyease-mens-running-shoe-1Fb6sV.jpg',
    nikeID: 207 },
  { name: 'Nike Air Zoom Pegasus FlyEase FlyKnit',
    discountPrice: 140,
    colorStyles:
     [ 'Dark Grey', 'Pure Platinum', 'Anthracite', 'Bright Crimson' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Pegasus',
       'FlyEase',
       'FlyKnit',
       'Dark Grey',
       'Pure Platinum',
       'Anthracite',
       'Bright Crimson',
       'Air',
       'Air Zoom',
       'Air Zoom Pegasus',
       'Air Zoom Pegasus FlyEase' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/39530e3c-2330-48b9-a7a6-72eb0e8c35ae/air-zoom-pegasus-36-flyease-mens-running-shoe-1Fb6sV.jpg',
    nikeID: 208 },
  { name: 'Nike Air Zoom Pegasus FlyEase FlyKnit',
    discountPrice: 150,
    colorStyles: [ 'Pistachio Frost', 'White', 'Black' ],
    type: 'Men Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Pegasus',
       'FlyEase',
       'FlyKnit',
       'Pistachio Frost',
       'White',
       'Black',
       'Air',
       'Air Zoom',
       'Air Zoom Pegasus',
       'Air Zoom Pegasus FlyEase' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/39530e3c-2330-48b9-a7a6-72eb0e8c35ae/air-zoom-pegasus-36-flyease-mens-running-shoe-1Fb6sV.jpg',
    nikeID: 209 },
  { name: 'Nike Air Zoom Pegasus FlyEase FlyKnit',
    discountPrice: 135,
    colorStyles: [ 'Black', 'Half Blue', 'White', 'Light Blue' ],
    type: 'Women Running Shoe',
    collection:
     [ 'Nike',
       'Air',
       'Zoom',
       'Pegasus',
       'FlyEase',
       'FlyKnit',
       'Black',
       'Half Blue',
       'White',
       'Light Blue',
       'Air',
       'Air Zoom',
       'Air Zoom Pegasus',
       'Air Zoom Pegasus FlyEase' ],
    image:
     'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/39530e3c-2330-48b9-a7a6-72eb0e8c35ae/air-zoom-pegasus-36-flyease-mens-running-shoe-1Fb6sV.jpg',
    nikeID: 210 }
]
  
// Format JSON object
var JSONformat = rawData.map((shoe) => (
    {
        item: shoe.name,
        type: shoe.type,
        price: shoe.discountPrice,
        image: shoe.image,
        collections: shoe.collection,
        colors: shoe.colorStyles,
        id: shoe.nikeID
    }
))

module.exports = JSONformat;
